In [3]:
import numpy as np

T = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("1. Array ndim:", T.ndim)
print("   Array shape:", T.shape)

T_added = T + T
print("added: Result of T + T:\n", T_added)

T_transposed = T.T
print("trasposed: Transposed shape:", T_transposed.shape)

T_reshaped = T.reshape(2, 6)
print("reshaped: Reshaped into (2, 6):\n", T_reshaped)


1. Array ndim: 2
   Array shape: (3, 4)
added: Result of T + T:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
trasposed: Transposed shape: (4, 3)
reshaped: Reshaped into (2, 6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
import numpy as np

def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

pairs = [
    (np.array([1, 0, 1]), np.array([1, 0, 1])),
    (np.array([1, 2, 3]), np.array([3, 2, 1])),
    (np.array([2, 0, 0]), np.array([0, 5, 0])),
]

for i, (u, v) in enumerate(pairs, start=1):
    l1_norm = np.linalg.norm(u, ord=1)
    l2_norm = np.linalg.norm(u, ord=2)

    similarity = cosine(u, v)

    print(f"Pair {i}:")
    print(f"  L1 Norm of u: {l1_norm}")
    print(f"  L2 Norm of u: {l2_norm:.4f}")
    print(f"  Cosine Similarity: {similarity:.4f}\n")



Pair 1:
  L1 Norm of u: 2.0
  L2 Norm of u: 1.4142
  Cosine Similarity: 1.0000

Pair 2:
  L1 Norm of u: 6.0
  L2 Norm of u: 3.7417
  Cosine Similarity: 0.7143

Pair 3:
  L1 Norm of u: 2.0
  L2 Norm of u: 2.0000
  Cosine Similarity: 0.0000

